---
env:
  node: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - typelint
  - react
rules:
  eol-last: 0
  no-trailing-spaces: 0
  func-names: 0
  comma-dangle: 0
  no-param-reassign: 0
  no-case-declarations: 0
  object-curly-spacing: 0
  no-use-before-define: 0
  global-require: 0
  no-underscore-dangle: 0
  one-var: 0
  one-var-declaration-per-line: 0
  max-len: 0
  valid-typeof: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  typelint/typelint: 2
extends: 'airbnb-base/legacy'
settings:
  typelint:
    models:
      json:
        swagger: 'schemas/petstore.yaml'
      redux:
        reducerPath: 'src/client/redux/reducer.js'
    useCache: false